### ISSUE TITLE
Current working directory is not a Cordova-based project.

### ISSUE THREAD

**Issue by Denubis** [oraad/cordova-react-template#3]
Hi folks,

When trying to spin this up, I get as far as cloning from template `cordova create CordovaReactApp au.edu.faims.CordovaReactApp CordovaReactApp --template cordova-react` , and running`cordova platform add android
` and it returns Current working directory is not a Cordova-based project.

I suspect there are some version games going on here. Thoughts on how I can improve replication/fix issue?

**Comment by ZanzyTHEbar** [comment]
I get the same issue, trying to add new platforms. Very dissapointing, would like to use this template.

**Comment by russosalv** [comment]
I have sam issue any updates?

**Comment by ZanzyTHEbar** [comment]
> I have sam issue any updates?

not from me, i gave up. Moved on to Capacitor and Ionic. They are newer platforms and nicer imo.

**Comment by Denubis** [comment]
We also moved onto Capacitor. It does its job.
